#!/bin/sh

alias ll="ls -l"
alias la="ls -A"
alias keydconfig="sudo vim /etc/keyd/default.conf"
# alias at="alacritty-themes"
alias at_clear_backups="rm ~/.config/alacritty/alacritty.yml.*"
alias terminal_clock='while echo -en "$(date)\r"; do sleep 1; done'
alias tclock='while echo -en "$(date)\r"; do sleep 1; done'
alias click='while echo -en "$(date)\r"; do sleep 1; done'
alias zrc="vim ~/.config/zsh/.zshrc"
alias zhis="vim ~/.cache/zsh/history"
alias arc="vim ~/.config/zsh/aliasrc"
alias ayml="vim ~/.config/alacritty/alacritty.yml"
alias vrc="vim ~/.vimrc"
alias prc="vim ~/.config/polybar/config.ini"
alias src="vim ~/.config/sxhkd/sxhkdrc"
alias piconf="vim ~/.config/picom.conf"
alias gnext="styli.sh -g -d ~/Pictures/Wallpapers"
alias next="styli.sh -d ~/Pictures/Wallpapers"
alias i3config="vim ~/.config/i3/config"
alias pwd="pwd | xclip -sel clipboard"

# Betterlockscreen
alias bl="betterlockscreen -u ~/Pictures/Wallpapers/ && eog /home/ginningolive/.cache/betterlockscreen/1-eDP-1/resize.png && eog /home/ginningolive/.cache/betterlockscreen/2-HDMI-1/resize.png"

# Animated backgrounds in gnome
alias start_hidamari="nohup sh -x ~/Documents/start_hidamari.sh &"
alias stop_hidamari="gnome-extensions enable WallpaperSwitcher@Rishu && flatpak kill io.github.jeffshee.Hidamari && next"
alias kill_hidamari="stop_hidamari"

# Animated backgrounds in i3
alias animated-background='back4.sh 0.01 $(fzf --query "Pictures/gifs/converted/")'

# Flatpaks
alias brave="flatpak run com.brave.Browser"

# List installed AUR packages
alias aur-list="pacman -Qem | expac --timefmt='%F %T' '%n %v %l' - | sort -k3"

# nvbn/thefuck
eval $(thefuck --alias)

# enable color support of ls and also add handy aliases

if [ -x /usr/bin/dircolors ]
then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
