vim.keymap.set('n', '<leader>h', ':nohlsearch<CR>')
vim.keymap.set('i', 'jk', '<Esc>', { noremap = true })
vim.keymap.set('c', 'jk', '<Esc>', { noremap = true })
vim.keymap.set('n', 'q', ':q <Enter>', { noremap = true })
vim.keymap.set('n', 'Q', ':q! <Enter>', { noremap = true })
vim.keymap.set('n', 'zz', ':w <Enter>', { noremap = true })
vim.keymap.set('n', 'zc', 'zz', { noremap = true })
vim.keymap.set('n', 'U', '<c-r>', { noremap = true })
vim.keymap.set('i', '(', '()<Left>', { noremap = true })
vim.keymap.set('i', '[', '[]<Left>', { noremap = true })
vim.keymap.set('i', '{', '{}<Left>', { noremap = true })
vim.keymap.set('n', '<leader>g', ':let @+ = expand("%")', { noremap = true })
vim.keymap.set('n', '<leader>s', ':setlocal spell!<CR>', { noremap = true })
vim.keymap.set('n', '<C-c>', 'gcc', { noremap = true })
vim.keymap.set('i', '<F5>', '<Esc>:w<CR>:!clear;python %<CR>', { noremap = true })
vim.keymap.set('n', '<F5>', '<Esc>:w<CR>:!clear;python %<CR>', { noremap = true })

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set('n', 'J', 'mzJ`z', { noremap = true })
vim.keymap.set('n', '<C-d>', '<C-d>zz', { noremap = true })
vim.keymap.set('n', '<C-u>', '<C-u>zz', { noremap = true })
vim.keymap.set('n', 'n', 'nzzzv', { noremap = true })
vim.keymap.set('n', 'N', 'Nzzzv', { noremap = true })
vim.keymap.set('x', '<leader>p', "\"_dp", { noremap = true })
vim.keymap.set('n', '<leader>d', "\"_d", { noremap = true })
vim.keymap.set('v', '<leader>d', "\"_d", { noremap = true })
vim.keymap.set('n', '<leader>y', "\"+y", { noremap = true })
vim.keymap.set('v', '<leader>y', "\"+y", { noremap = true })
vim.keymap.set('n', '<leader>Y', "\"+Y", { noremap = true })

vim.keymap.set("n", "<leader>S", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })

-- vim.keymap.set('n', '<C-f>', '<cmd>silent !tmux neww tmux-sessionizer<CR>')
-- vim.keymap.set('n', '<leader>f', function()
--     vim.lsp.buf.format()
-- end)

-- Quickfix navigation
-- vim.keymap.set('n', '<C-k>', '<cmd>cnext<CR>zz')
-- vim.keymap.set('n', '<C-j>', '<cmd>cprev<CR>zz')
-- vim.keymap.set('n', '<leader>k', '<cmd>lnext<CR>zz')
-- vim.keymap.set('n', '<leader>j', '<cmd>lprev<CR>zz')

-- telescope
-- local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
-- vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
-- vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
-- vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })

-- vim.keymap.set('n', '<leader>ff', ':Telescope find_files hidden=true <Enter>', { noremap = true })
-- vim.keymap.set('n', '<leader>fg', ':Telescope live_grep <Enter>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>ff', ':lua require"telescope.builtin".find_files({ hidden = true })<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<Leader>fg', ':lua require"telescope.builtin".live_grep({ hidden = true })<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<leader>fb', ':Telescope buffers <Enter>', { noremap = true })
vim.keymap.set('n', '<leader>fh', ':Telescope help_tags <Enter>', { noremap = true })
vim.keymap.set('n', '<leader>fo', ':Telescope oldfiles <Enter>', { noremap = true })

--NvimTree
vim.keymap.set('n', '<leader>e', ':NvimTreeToggle<CR>', { noremap = true })
