#!/usr/bin/sh

pkill sxhkd ; sxhkd &
sxhkd -c ~/.config/bspwm/bspwm-sxhkdrc &
~/.screenlayout/eDP-1.sh
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Discord desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

notify-send "bspwm reloaded"
