#!/bin/bash

if pgrep -x "stalonetray" > /dev/null
then
    killall stalonetray
else
    stalonetray -c ~/.config/stalonetray/.stalonetrayrc &
    xdotool sleep 0.1
    xdotool getactivewindow windowmove 3810 48
    xdotool sleep 8
    killall stalonetray
fi
