{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    i3
    rofi-wayland
    arandr
    sxhkd
    stow
    picom
    stalonetray
    xdotool
    ydotool
    brightnessctl
    playerctl
    flameshot
    lxappearance
    nwg-look
    dunst
    feh
    btop
    htop
    neofetch
    cava
    mangohud
    trashy
    autojump
    tldr
    xclip
    tmux
    screenkey
    cmatrix
    lolcat
    gnome.gnome-boxes
    gnome.gnome-calculator
    gpick
    micro
    redshift
    sl
    x11vnc
    wayvnc
    polybar
    waybar
    eww
    hyprland
    hyprlandPlugins.hyprwinwrap
    hyprpaper
    swaybg
    swaylock
    # wpaperd
    swww
    mpvpaper
    waypaper
    mpv
    opentabletdriver
    hyprshot
    hyprpicker
    wshowkeys
    awesome
    bspwm
    wmctrl
    screenfetch
    alacritty
    kitty
    glava
    hyprlock
    hypridle
    krusader
    ranger
    lf
    uxplay
    wlsunset
    wlogout
    wl-clipboard
    superTuxKart
    helix
    vlc
    fzf
    neovim
    nix-search-cli
    clonehero
    pavucontrol
    brave
    celeste64
    easyeffects
    # obs-studio
    parsec-bin
    cura
    vesktop
    discord
    mupen64plus
    jamulus
    anki
    runelite
    audacity
    krita
    remmina
    qpwgraph
    synthesia
    plover.dev
    killall
    appimage-run
    pywal
    python310Full
    dbus
    alsa-utils
    cifs-utils
    xorg.xf86inputsynaptics
    pulseaudioFull
    mplayer
    cinnamon.mint-themes
    autotiling
    # xarchive - https://search.nixos.org/packages?channel=unstable&show=xarchive&from=0&size=50&sort=relevance&type=packages&query=xarchive
    xarchiver
    arrpc
    glxinfo
    input-leap
    ffmpeg
    # osu-lazer-bin
    libnotify
    # linux-wallpaperengine
    jq
    slurp
    grim
    xfce.xfce4-whiskermenu-plugin
    pistol
    file
    davinci-resolve
    # sunshine
    # pywalfox-native
    asciiquarium
    discover-overlay
    kdePackages.plasma-browser-integration
  ];
}
